# Generated by Django 6.0.1 on 2026-01-31 07:10

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], max_length=50, verbose_name='User role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Category Image')),
                ('category_description', models.CharField(max_length=255, verbose_name='Category Description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category Slug')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='customer_profiles/', verbose_name='Profile picture')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('door_number', models.CharField(blank=True, max_length=100, verbose_name='Door number')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Street')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='Pincode')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vendor_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Vendor')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/', verbose_name='company logo')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('business_registration_number', models.CharField(max_length=255, verbose_name='Registration number')),
                ('gst_id', models.CharField(max_length=255, verbose_name='GST number')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('product_image', models.ImageField(upload_to='product_images/', verbose_name='Product Image')),
                ('product_description', models.TextField(verbose_name='Product Description')),
                ('product_specifications', models.TextField(blank=True, null=True, verbose_name='Product Specifications')),
                ('product_stock', models.PositiveIntegerField(verbose_name='Product Stock')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('product_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Product Discount')),
                ('product_price_after_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Product Price After Discount')),
                ('product_availability', models.BooleanField(default=True, verbose_name='Product Availability')),
                ('product_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Product Created At')),
                ('product_updated_at', models.DateTimeField(auto_now=True, verbose_name='Product Updated At')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Product Slug')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory', to_field='slug', verbose_name='Category')),
                ('product_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendorprofile', verbose_name='Product Vendor')),
            ],
        ),
    ]
