# Generated by Django 5.2.10 on 2026-01-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('category_image', models.ImageField(upload_to='category_images/', verbose_name='Category Image')),
                ('category_description', models.CharField(max_length=255, verbose_name='Category Description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category Slug')),
            ],
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
