# Generated by Django 5.2.10 on 2026-01-29 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Category Image')),
                ('category_description', models.CharField(max_length=255, verbose_name='Category Description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category Slug')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='addresses', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('contry', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('door_number', models.CharField(blank=True, max_length=100, verbose_name='Door number')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Street')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='Pincode')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='company_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
