# Generated by Django 5.2.10 on 2026-01-29 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productcategory_useraddress_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='addresses', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
