# Generated by Django 5.2.10 on 2026-01-30 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_useraddress_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('product_image', models.ImageField(upload_to='product_images/', verbose_name='Product Image')),
                ('product_description', models.TextField(verbose_name='Product Description')),
                ('product_specifications', models.TextField(blank=True, null=True, verbose_name='Product Specifications')),
                ('product_stock', models.PositiveIntegerField(verbose_name='Product Stock')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('product_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Product Discount')),
                ('product_price_after_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Product Price After Discount')),
                ('product_availability', models.BooleanField(default=True, verbose_name='Product Availability')),
                ('product_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Product Created At')),
                ('product_updated_at', models.DateTimeField(auto_now=True, verbose_name='Product Updated At')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Product Slug')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory', to_field='slug', verbose_name='Category')),
                ('product_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendorprofile', verbose_name='Product Vendor')),
            ],
        ),
    ]
